[package]
name = "imagers"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
dotenvy = "0.15.7"
lapin = "4.11.0"
serde = "1.0.229"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.146.1"
tracing-subscriber = "0.3.23"
uuid = {features = ["v4"],version = "1.26.1"}
chrono = "0.4.45"
